### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by real-felix** [PistonDevelopers/dev_menu#28]
The syntax

    let mut menu = dev_menu::Menu<Settings>::new();

is not valid in Rust, for example.

Furthermore, I cannot make the example work:

```
error[E0599]: no method named `events` found for type `piston_window::PistonWindow<sdl2_window::Sdl2Window>` in the current scope
  --> src/main.rs:72:30
   |
72 |         for e in self.window.events() {
   |                              ^^^^^^ field, not a method
   |
   = help: did you mean to write `self.window.events` instead of `self.window.events(...)`?
```

I think this was the way to do in an old version of Piston. And inside the loop:

```
error[E0277]: the trait bound `piston_window::Input: input::generic_event::GenericEvent` is not satisfied
  --> src/main.rs:73:18
   |
73 |             menu.event(&event, &mut ());
   |                  ^^^^^ the trait `input::generic_event::GenericEvent` is not implemented for `piston_window::Input`
```

The code has not been updated for years. All those clues let me suppose this package is no more maintained. Am I right?

PS: I am using the last version of Piston.

**Comment by bvssvni** [comment]
The example in README is outdated. Take a look at https://github.com/PistonDevelopers/skeletal_animation_demo to see an updated example.

**Comment by real-felix** [comment]
Thank you for your answer. I suppose that I can close this issue since you created an appropriate one.

I have only a little question because maybe I misunderstood the purpose of this crate: I want to implement a main menu in my game (like "play", "high score", etc.). Is this the right crate?

**Comment by bvssvni** [comment]
You could use it for a main menu, I guess. Otherwise, take a look at [Conrod](https://github.com/pistondevelopers/conrod).

**Comment by real-felix** [comment]
I tried Conrod, it fit well to my needs. Thank you for your quick answer.
